### ISSUE TITLE
email validation issue

### ISSUE THREAD

**Issue by Yurtledaturtle** [Yurtledaturtle/SignUp#1]
Discovered a last minute blocker on sinatra sign up app where the front end validation i had recently added seems to disallow my sign up entry from being stored in the database.  If I comment the validation out, the entries entered will be stored (without any validation), so I'm not sure if i'm missing another piece to the validation (on the front end or the back end) or if something else is at play.  Either way, I'm not so sure how to proceed, so I'm in need of some guidance....

**Comment by rapala61** [comment]
Lets meet

**Comment by Yurtledaturtle** [comment]
great!
